import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          welcome to <a href="/">a blog?</a>
        </h1>

        <p className={styles.description}>
          Get started by editing, i'm trying to see how far thsi line of text goes so here goes nothing - ok wow it goes so far but i need to see
          ig it can go further. i'm trying to see how far thsi line of text goes so here goes nothing
         
        </p>

        <div className={styles.grid}>
          <a href="/split" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API. i'm trying to see how far thsi line of text goes so here goes nothing</p>
          </a>

          <a href="/split" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes! i'm trying to see how far thsi line of text goes so here goes nothing</p>
          </a>

          <a
            href="/split"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects. i'm trying to see how far thsi line of text goes so here goes nothing</p>
          </a>

          <a
            href="/split"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel. Just making this longer yeah - how long can this go?
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <p>
          Hosted on <a href="https://github.com/malgamves">GitHub</a> built by <a href="https://malgamves.dev">Daniel</a>
        </p>
      </footer>
    </div>
  )
}
