import Head from 'next/head'
//import Image from 'next/image'
import Link from 'next/link'

import styles from '../styles/Home.module.css'

export default function Home() {
    return (
        <div className={styles.containerblog}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.mainblog}>
                <div className={[styles.split, styles.left].join(" ")}>
                    <div className={styles.centered}>
                        <h1 className={styles.title}>
                            blog post title
                        </h1>
                        <p className={styles.descriptionleft}>by author, written on date</p>

                        <p className={styles.back}>
                            <Link href="/">&larr; go back home</Link>
                        </p>
                    </div>
                </div>

                <div className={[styles.split, styles.right].join(" ")}>
                    <div className={styles.centered}>
                        <h2>John Doe</h2>
                        <p> Suspendisse ornare diam tortor, et interdum enim maximus non. Vivamus pretium pharetra eleifend. Phasellus varius dui quis vulputate congue. Aenean neque enim, fringilla vulputate sem eu, consequat sagittis lectus. Proin a massa dui. Vivamus eu eros quis purus vulputate efficitur. Cras quis placerat eros.
                             Pellentesque commodo posuere lacus, ac faucibus nibh. Quisque ornare in lacus sit amet consectetur. Cras varius luctus nisi vitae vehicula. sodales, metus est sagittis turpis, maximus fringilla ex risus et tortor. Pellentesque porta tortor lorem, at lacinia turpis maximus nec. Suspendisse ac tincidunt eros, in volutpat ante.

                            Quisque ut blandit ante, sed sagittis arcu. In vehicula interdum nunc, eget rhoncus odio porttitor eget. Integer nisi lectus, commodo id blandit a, porttitor semper metus. Curabitur euismod lacus nulla, eget luctus magna rutrum vel. Suspendisse potenti. Aenean luctus risus eu ex tristique, vitae euismod libero cursus. Proin posuere nibh dapibus libero ullamcorper gravida. Suspendisse potenti. Curabitur mollis feugiat rhoncus. Cras vitae dapibus magna. Donec bibendum eu elit et lobortis. Nunc pretium est non leo semper commodo. Morbi fringilla nisi libero, ac fringilla felis vestibulum non. Donec volutpat leo justo, eget ullamcorper sem rutrum at. Phasellus hendrerit dui vitae enim sodales ultricies eu et risus. </p>
                    </div>
                </div>
            </main>

        </div>
    )
}
