import Head from 'next/head'
import Image from 'next/image'

import fetch from 'cross-fetch'
import { server } from '../config';

import { ApolloClient, InMemoryCache, gql, HttpLink } from '@apollo/client';

import BlogList from '../components/BlogList'

import styles from '../styles/Home.module.css'

export default function Home({ posts }) {
  console.log(posts)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org"> the future of content</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <BlogList allBlogs={posts.posts} />

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}


export async function getStaticProps() {

  const client = new ApolloClient({
    link: new HttpLink({ uri: `${server}/graphql`, fetch }),
    cache: new InMemoryCache()
  });
  
  const { data } = await client.query({
    query: gql`
          query {
              posts {
                data {
                  id
                  attributes {
                    title
                    date
                    body
                    slug
                    author
                  }
                }
              }
      }
    `
  })


  return {
    props: {
      posts: data,
    },
  }
}